
import React, { useEffect, useRef } from 'react';
import { X } from 'lucide-react';
import { Html5QrcodeScanner } from 'html5-qrcode';

interface BarcodeScannerProps {
  onScan: (code: string) => void;
  onClose: () => void;
}

export const BarcodeScanner: React.FC<BarcodeScannerProps> = ({ onScan, onClose }) => {
  const scannerRef = useRef<any>(null);
  const onScanRef = useRef(onScan); // Keep track of latest callback

  useEffect(() => {
    onScanRef.current = onScan;
  }, [onScan]);
  
  useEffect(() => {
    // "reader" matches the id of the div below
    const scanner = new Html5QrcodeScanner(
      "reader",
      { 
        fps: 10, 
        qrbox: 250,
        aspectRatio: 1.0,
        rememberLastUsedCamera: true,
        showTorchButtonIfSupported: true
      },
      /* verbose= */ false
    );
    scannerRef.current = scanner;

    scanner.render(
      (decodedText: string) => {
        // Success callback
        // Call the latest onScan function stored in ref
        if (onScanRef.current) {
            onScanRef.current(decodedText);
        }
      }, 
      (errorMessage: string) => {
        // Parse error, ignore to prevent console spam
      }
    );

    // Cleanup on unmount
    return () => {
      if (scannerRef.current) {
        try {
          scannerRef.current.clear().catch((e: any) => console.warn("Scanner cleanup warning", e));
        } catch (e) {
          // Ignore cleanup errors
        }
      }
    };
  }, []); // Run once on mount

  return (
    <div className="fixed inset-0 z-[90] bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
      {/* Custom Styles for the Library Widget */}
      <style>{`
        #reader {
            border: none !important;
            font-family: inherit !important;
        }
        #reader__scan_region {
            background: #f8fafc;
            border-radius: 16px;
            overflow: hidden;
        }
        #reader__dashboard_section_csr span, 
        #reader__dashboard_section_swaplink {
            display: block;
            margin-bottom: 8px;
            font-size: 14px;
            font-weight: 600;
            color: #4b5563;
        }
        /* Style the Buttons (Start/Stop/Request Permissions) */
        #reader button {
            background-color: #4f46e5 !important; /* brand-600 */
            color: white !important;
            border: none !important;
            padding: 10px 20px !important;
            border-radius: 12px !important;
            font-weight: bold !important;
            font-size: 14px !important;
            cursor: pointer !important;
            margin-top: 8px !important;
            width: 100%;
            box-shadow: 0 4px 6px -1px rgba(79, 70, 229, 0.2);
            transition: all 0.2s;
        }
        #reader button:active {
            transform: scale(0.98);
        }
        /* Style the Select Dropdown */
        #reader select {
            padding: 10px !important;
            border: 1px solid #e5e7eb !important;
            border-radius: 12px !important;
            margin-bottom: 10px !important;
            width: 100% !important;
            font-size: 14px !important;
            background-color: white !important;
            outline: none !important;
        }
        /* Hide unnecessary text links or style them */
        #reader__dashboard_section_swaplink {
            text-decoration: underline !important;
            color: #6366f1 !important;
            cursor: pointer !important;
            margin-top: 10px;
        }
        /* Header text generated by lib */
        #reader__header_message {
            display: none !important;
        }
        /* Status text */
        #reader__status_span {
            font-size: 12px !important;
            color: #9ca3af !important;
        }
        img[alt="Info icon"] {
            display: none;
        }
      `}</style>

      <div className="bg-white rounded-3xl w-full max-w-sm overflow-hidden shadow-2xl relative animate-[scale-in_0.2s_ease-out]">
        {/* Modal Header */}
        <div className="p-4 flex justify-between items-center border-b border-gray-100 bg-gray-50">
            <h3 className="font-bold text-gray-800 text-lg">Scan Barcode</h3>
            <button 
                onClick={onClose} 
                className="text-gray-500 hover:text-gray-800 bg-white border border-gray-200 p-2 rounded-full shadow-sm active:scale-95 transition-all"
            >
                <X size={20} />
            </button>
        </div>
        
        {/* Scanner Container */}
        <div className="p-6 bg-white">
            <div id="reader" className="w-full"></div>
            <p className="text-center text-xs text-gray-400 mt-4 font-medium">Point camera at a barcode to add to cart.</p>
        </div>
      </div>
    </div>
  );
};